### ISSUE TITLE
Panic Exception Encountered During Report Generation with bsxplorer-category

### ISSUE THREAD

**Issue by komais** [shitohana/BSXplorer#15]
Dear Author ,

I hope this message finds you well. I am reaching out to report an issue I encountered while utilizing your tool, bsxplorer-category. My workflow progressed smoothly through reading the genome, processing cytosines, calculating p-values, and preparing the data. However, the process fails when attempting to initialize the report reader and render the final output.

Environment Details:

* Tool: bsxplorer-category
* Python Version: 3.10
* Steps to Reproduce:

I initiated the process with the following command:    bsxplorer-category --ticks upstream TSS Gene TES downstream config2.txt 

Input files were successfully read from /work/share/acuhtwkcu9/RD/saile_bs/pipeline_test/test/bsx/...
Processing stages including cytosine reading and p-value calculations completed without errors.
The error occurs after all preprocessing steps, during the generation of the final report.

* Error Description:
The error is a panic originating from a Rust component (PyO3 and polars) integrated with Python, specifically pointing to an attempt to perform division with NoneType operands. The detailed stack trace suggests an issue within the data transformation pipeline, likely during the application of a lambda function or data manipulation step.

* Error Message:

Working directory: /work/share/acuhtwkcu9/RD/saile_bs/pipeline_test/test/bsx
Plots directory: /work/share/acuhtwkcu9/RD/saile_bs/pipeline_test/test/bsx/plots
Report name: Metagene_Report_01-07-24_17-11-43
Block size (Mb): 50
Summary function: wmean
Threads: False

Upstream | Body | Downstream (bins): 50 | 100 | 50

P-value for cytosines: 0.05P-value for region: 0.05Minimal coverage: 2Save categories? - TrueClustermap variance filtering quantile: 0.75
Confidence band alpha for line_plot: 0.95
Smoothing function window width: 10
Heat_map dimensions (hor, ver): (100, 100)

Separate strands? - False
Export format: pdf
Tick_names: ['upstream', 'TSS', 'Gene', 'TES', 'downstream']

RUN STARTED at 01/07/24 17:11:44

Genome read from /work/share/acuhtwkcu9/RD/saile_bs/pipeline_test/test/bsx/gene.ensemble.gff
Reading from /work/share/acuhtwkcu9/RD/saile_bs/pipeline_test/test/bsx/data/a.txt
Reading cytosines |################################| 100.0%
Writing p_values file into: /work/share/acuhtwkcu9/RD/saile_bs/pipeline_test/test/bsx/a.parquet
Calculating p-values |################################| 100.0%
Done

Total cytosine residues: 48318155.
Average proportion of methylated reads to total reads for cytosine residue: 0.06274352376075308
From a.parquet
Reading p_values |################################| 100.0%
CHG	Total sites: 7815746, methylated: 37627	(0.48%)
CG	Total sites: 1677383, methylated: 1375827	(82.02%)
CHH	Total sites: 26166784, methylated: 179315	(0.69%)
Initializing report reader.
Reading report from /work/share/acuhtwkcu9/RD/saile_bs/pipeline_test/test/bsx/a.parquet
 |@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@| 170/170 Mb [0:00:19 | ETA: 0:00:00]
DONE

Reading from /work/share/acuhtwkcu9/RD/saile_bs/pipeline_test/test/bsx/data/a.txt
Reading cytosines |################################| 100.0%
Writing p_values file into: /work/share/acuhtwkcu9/RD/saile_bs/pipeline_test/test/bsx/a.parquet
Calculating p-values |################################| 100.0%
Done

Total cytosine residues: 48318155.
Average proportion of methylated reads to total reads for cytosine residue: 0.06274352376075308
From a.parquet
Reading p_values |################################| 100.0%
CHH	Total sites: 26166784, methylated: 179315	(0.69%)
CG	Total sites: 1677383, methylated: 1375827	(82.02%)
CHG	Total sites: 7815746, methylated: 37627	(0.48%)
Initializing report reader.
Reading report from /work/share/acuhtwkcu9/RD/saile_bs/pipeline_test/test/bsx/a.parquet
 |@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@| 170/170 Mb [0:00:18 | ETA: 0:00:00]
DONE

thread '<unnamed>' panicked at py-polars/src/map/series.rs:2466:44:
called `Result::unwrap()` on an `Err` value: PyErr { type: <class 'TypeError'>, value: TypeError("unsupported operand type(s) for /: 'NoneType' and 'NoneType'"), traceback: Some(<traceback object at 0x2afe82e3cd80>) }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
--- PyO3 is resuming a panic after fetching a PanicException from Python. ---
Python stack trace below:
Traceback (most recent call last):
  File "/software/conda/lib/python3.10/site-packages/polars/expr/expr.py", line 4021, in __call__
    result = self.function(*args, **kwargs)
  File "/software/conda/lib/python3.10/site-packages/polars/expr/expr.py", line 4356, in wrap_f
    return x.map_elements(
  File "/software/conda/lib/python3.10/site-packages/polars/series/series.py", line 5335, in map_elements
    self._s.apply_lambda(function, pl_return_dtype, skip_nulls)
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: PyErr { type: <class 'TypeError'>, value: TypeError("unsupported operand type(s) for /: 'NoneType' and 'NoneType'"), traceback: Some(<traceback object at 0x2afe82e3cd80>) }
Traceback (most recent call last):
  File "/software/conda/bin/bsxplorer-category", line 8, in <module>
    sys.exit(category())
  File "/software/conda/lib/python3.10/site-packages/bsxplorer/cons_master.py", line 17, in category
    _save(CategoryScript())
  File "/software/conda/lib/python3.10/site-packages/bsxplorer/cons_master.py", line 5, in _save
    html = script.main()
  File "/software/conda/lib/python3.10/site-packages/bsxplorer/cons_utils.py", line 495, in main
    rendered = Renderer(self.args).category(metagene_files, sample_region_stats)
  File "/software/conda/lib/python3.10/site-packages/bsxplorer/cons_utils.py", line 770, in category
    context_block = self.metagene_context_block(categorised, filters, draw_cm=False)
  File "/software/conda/lib/python3.10/site-packages/bsxplorer/cons_utils.py", line 650, in metagene_context_block
    fig = line_plot.draw_mpl(smooth=self.args.smooth, confidence=self.args.confidence, **tick_args)
  File "/software/conda/lib/python3.10/site-packages/bsxplorer/Plots.py", line 347, in draw_mpl
    lp.draw_mpl((fig, axes), smooth, label, confidence, linewidth, linestyle, major_labels, minor_labels, show_border)
  File "/software/conda/lib/python3.10/site-packages/bsxplorer/Plots.py", line 197, in draw_mpl
    lower, data, upper = self.__get_x_y(df, smooth, confidence, self.stat)
  File "/software/conda/lib/python3.10/site-packages/bsxplorer/Plots.py", line 86, in __get_x_y
    .with_columns(
  File "/software/conda/lib/python3.10/site-packages/polars/dataframe/frame.py", line 8315, in with_columns
    return self.lazy().with_columns(*exprs, **named_exprs).collect(_eager=True)
  File "/software/conda/lib/python3.10/site-packages/polars/lazyframe/frame.py", line 1940, in collect
    return wrap_df(ldf.collect())
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: PyErr { type: <class 'TypeError'>, value: TypeError("unsupported operand type(s) for /: 'NoneType' and 'NoneType'"), traceback: Some(<traceback object at 0x2afe82e3cd80>) }

* Additional Information:
The error might be related to missing or null values in the dataset being processed, leading to an unsupported operation during data transformation for plotting.

Thank you for your attention to this matter. I appreciate your efforts in maintaining this valuable tool and look forward to a resolution or guidance on how I can contribute to fixing this issue.

Best regards,

**Comment by komais** [comment]
thank you very much
